### ISSUE TITLE
clip or  no clip the noise data 

### ISSUE THREAD

**Issue by ffmm123** [fenghansen/PNNP#1]
你好，请问，您在数据处理过程中，对噪声数据归一化不进行clip有效么？我保留bl以下的数据训练后，去噪后图像的残留噪声孤立点的颜色比clip后训练的点的颜色更深，整个去噪图像看起来有很多麻点且这些点偏色，总之不进行clip的效果比clip之后的效果差。

**Comment by fenghansen** [comment]
训练和推理的时候是否进行clip要统一，统一clip和统一不clip都是可行的，不统一的话总会出现严重的artifacts
在我的实验中，统一不clip更好一些（最大值最好还是clip一下）

**Comment by ffmm123** [comment]
谢谢解答，因为在我的实验中，光照在千分之一左右，理论上不做clip效果较好，但实际上大多值不做clip后为负值，模型很难将这些负值向gt靠近，所以，测试图像出现很多的孤立点各通道颜色严重不平衡导致偏色。

**Comment by fenghansen** [comment]
残留噪声很大的情况下显得偏色一般是白平衡增益不均衡（一般r:g:b约2:1:2）导致的偏紫？其他的偏色一般都是black level歪了的问题，你clip掉了的话就更不知道均值是多少了。建议查一下无光暗帧的darkshading，看看均值是不是明显偏离black level。
