### ISSUE TITLE
Open Source Code

### ISSUE THREAD

**Issue by mldemox** [fenghansen/PNNP#2]
Thank you for your outstanding work, is there any open source code in the pipeline these days?

**Comment by fenghansen** [comment]
I'm afraid that we have no plans to release the complete open-source code before the paper is accepted.

**Comment by mldemox** [comment]
Ok, thanks for the reply and hopefully your work will be accepted quickly!

hansen97 ***@***.***> 于2024年7月25日周四 14:34写道：
