### ISSUE TITLE
SID Sony数据集ELD方法结果不一致

### ISSUE THREAD

**Issue by Cynicarlos** [fenghansen/PNNP#3]
论文中SID Sony数据集上ELD(PAMI Version)的结果似乎与原文不一致

![image](https://github.com/user-attachments/assets/c40bbe14-1476-48ca-91ef-3d71458d5980)
这是ELD(PAMI Version)原论文中的结果
![image](https://github.com/user-attachments/assets/87ef6aa3-37fa-4d4e-af28-1b4284ce56f2)

**Comment by fenghansen** [comment]
权重一致，前作PMN中有说明原因，欢迎访问对应的github
Comparision
table Note:

The quantitative results on the SID dataset is different from the provided results in ELD (TPAMI) because only the central area is compared in ELD (TPAMI) on the SID dataset.

**Comment by Cynicarlos** [comment]
Got it. Thx.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月20日(周五) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fenghansen/PNNP] SID Sony数据集ELD方法结果不一致 (Issue #3)




 
权重一致，前作PMN中有说明原因，欢迎访问对应的github
 Comparision
 table Note:
 
The quantitative results on the SID dataset is different from the provided results in ELD (TPAMI) because only the central area is compared in ELD (TPAMI) on the SID dataset.
